"""Source-neutral conversion into Speech Synthesis Markdown (SSMD)."""

from __future__ import annotations

from .books import convert_book, inspect_book
from .bundle import load_book_bundle, validate_book_bundle, write_book_bundle
from .converter import Converter, convert
from .errors import (
    BookBundleError,
    BookBundleValidationError,
    BookError,
    ChapterSelectionError,
    MissingDependencyError,
    SSMDConvertError,
    UnsupportedBookSourceError,
    UnsupportedInputError,
)
from .models import (
    Book,
    BookChapter,
    BookInspection,
    BookInspectionChapter,
    ConversionResult,
    Document,
    Section,
    SourceInfo,
)

try:
    from ._version import version as __version__
except ImportError:  # generated by setuptools-scm in builds/editable installs
    try:
        from importlib.metadata import version

        __version__ = version("ssmdconvert")
    except Exception:  # pragma: no cover - bare source tree
        __version__ = "0+unknown"

__all__ = [
    "Book",
    "BookBundleError",
    "BookBundleValidationError",
    "BookChapter",
    "BookError",
    "BookInspection",
    "BookInspectionChapter",
    "ChapterSelectionError",
    "ConversionResult",
    "Converter",
    "Document",
    "MissingDependencyError",
    "SSMDConvertError",
    "Section",
    "SourceInfo",
    "UnsupportedBookSourceError",
    "UnsupportedInputError",
    "__version__",
    "convert",
    "convert_book",
    "inspect_book",
    "load_book_bundle",
    "validate_book_bundle",
    "write_book_bundle",
]
